@startuml
TcpServerBase <|-- TcpServerCmd
TcpServerBase <|-- TcpServerTel
TcpServerBase <|-- TcpServerEvent
TcpServerBase <|-- TcpServerEvent3
TcpServer *-- TcpServerCmd
TcpServer *-- TcpServerTel
@enduml
